FROM node:18.1-alpine3.15 as build

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM node:18.1-alpine3.15 as runner

WORKDIR /app

COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/.env /app/.env
COPY --from=build /app/start.sh /app/start.sh

EXPOSE 3001

ENTRYPOINT ["sh","start.sh"]
