version: '3.8'

services:
  alfa_postgres:
    image: postgres:12-alpine
    container_name: alfa_postgres
    restart: always
    environment:
      - POSTGRES_DB=alfa_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Alfa@2022
    volumes:
      - alfa_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - alfa_postgres_network

  alfa_api:
    image: alfa_api:latest
    container_name: alfa_api
    build:
      context: .  
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - alfa_postgres
    ports:
      - 3333:3333
    networks:
      - nginx_proxymanager
      - alfa_postgres_network

volumes:
  alfa_pg_data:

networks:
  nginx_proxymanager:
    external: true
  alfa_postgres_network:
    name: alfa_postgres_network