version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: alfa-api
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: alfa-db
    ports:
      - 5435:5432
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
