@Library('jenkins_lib@main')
import br.com.alfa.Commands
import br.com.alfa.ProjectMetadata

def projectMetadata = new ProjectMetadata();
def cmd = new Commands();

projectMetadata.projectName = "alfa-be"
projectMetadata.dockerfile = "Dockerfile"
projectMetadata.language = "alfa"
projectMetadata.version = "1.0"
projectMetadata.sourcesPath = "src"

cmd.exec(projectMetadata);
